# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'FireBaseProof' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for FireBaseProof
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FacebookLogin'
  #pod 'Firebase/Crashlytics'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
end
